enstb_data_management:
    resource: "@EnstbDataManagementBundle/Resources/config/routing.yml"
    prefix:   /data

enstb_visplat:
    resource: "@EnstbVisplatBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administrator

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administrator