enstb_visplat_homepage:
    pattern:  /
    defaults: { _controller: EnstbVisplatBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: EnstbVisplatBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern: /logout